#!/bin/bash
#chkconfig:2345 80 05
#description: myservice

if [ -f ~/.bash_profile ];
then
    . ~/.bash_profile
fi

case "$1" in 
start)
	su - root "/root/ming/owebserver/SEMain/jhss_start.sh"
	;;
stop)
	su - root "/root/ming/webserver/SEMain/jhss_stop.sh"
	;;
restart)
	su - root "/root/ming/webserver/SEMain/jhss_restart.sh"
	;;
*)
	echo "Usage: sudo service sshd {start|stop|restart}"
esac

